export type EmojiCategory =
  | "smileys"
  | "people"
  | "nature"
  | "food"
  | "activity"
  | "travel"
  | "objects"
  | "symbols";

export type EmojiEntry = {
  glyph: string;
  name: string;
  keywords: string[];
  category: EmojiCategory;
};

export const EMOJI_CATEGORIES: { id: EmojiCategory; label: string; icon: string }[] = [
  { id: "smileys", label: "Smileys", icon: "😀" },
  { id: "people", label: "People", icon: "👋" },
  { id: "nature", label: "Nature", icon: "🌸" },
  { id: "food", label: "Food", icon: "🍕" },
  { id: "activity", label: "Activity", icon: "🎉" },
  { id: "travel", label: "Travel", icon: "✈️" },
  { id: "objects", label: "Objects", icon: "💡" },
  { id: "symbols", label: "Symbols", icon: "❤️" },
];

function entry(
  glyph: string,
  name: string,
  category: EmojiCategory,
  keywords: string[] = [],
): EmojiEntry {
  return { glyph, name, category, keywords };
}

export const EMOJI_CATALOG: EmojiEntry[] = [
  entry("😀", "grinning face", "smileys", ["smile", "happy", "grin"]),
  entry("😃", "grinning face with big eyes", "smileys", ["smile", "happy"]),
  entry("😄", "grinning face with smiling eyes", "smileys", ["smile", "happy"]),
  entry("😁", "beaming face with smiling eyes", "smileys", ["smile", "grin"]),
  entry("😆", "grinning squinting face", "smileys", ["laugh", "happy"]),
  entry("😅", "grinning face with sweat", "smileys", ["relief", "nervous"]),
  entry("😂", "face with tears of joy", "smileys", ["laugh", "lol", "cry"]),
  entry("🤣", "rolling on the floor laughing", "smileys", ["laugh", "rofl"]),
  entry("😊", "smiling face with smiling eyes", "smileys", ["smile", "blush"]),
  entry("😇", "smiling face with halo", "smileys", ["angel", "innocent"]),
  entry("🙂", "slightly smiling face", "smileys", ["smile"]),
  entry("😉", "winking face", "smileys", ["wink", "flirt"]),
  entry("😌", "relieved face", "smileys", ["calm", "peace"]),
  entry("😍", "smiling face with heart-eyes", "smileys", ["love", "heart", "crush"]),
  entry("🥰", "smiling face with hearts", "smileys", ["love", "heart", "adore"]),
  entry("😘", "face blowing a kiss", "smileys", ["kiss", "love"]),
  entry("😋", "face savoring food", "smileys", ["yum", "tasty"]),
  entry("😜", "winking face with tongue", "smileys", ["wink", "joke"]),
  entry("🤪", "zany face", "smileys", ["goofy", "wild"]),
  entry("🤗", "smiling face with open hands", "smileys", ["hug"]),
  entry("🤔", "thinking face", "smileys", ["hmm", "consider"]),
  entry("🤨", "face with raised eyebrow", "smileys", ["skeptical"]),
  entry("😐", "neutral face", "smileys", ["meh", "blank"]),
  entry("😑", "expressionless face", "smileys", ["blank"]),
  entry("😶", "face without mouth", "smileys", ["silent"]),
  entry("😏", "smirking face", "smileys", ["smirk"]),
  entry("😒", "unamused face", "smileys", ["meh", "sideeye"]),
  entry("🙄", "face with rolling eyes", "smileys", ["eyeroll"]),
  entry("😬", "grimacing face", "smileys", ["awkward"]),
  entry("😔", "pensive face", "smileys", ["sad", "sorry"]),
  entry("😪", "sleepy face", "smileys", ["tired"]),
  entry("😴", "sleeping face", "smileys", ["sleep", "zzz"]),
  entry("😷", "face with medical mask", "smileys", ["sick", "mask"]),
  entry("🤒", "face with thermometer", "smileys", ["sick", "fever"]),
  entry("🤢", "nauseated face", "smileys", ["sick", "gross"]),
  entry("🤮", "face vomiting", "smileys", ["sick", "puke"]),
  entry("🥴", "woozy face", "smileys", ["drunk", "dizzy"]),
  entry("😵", "face with crossed-out eyes", "smileys", ["dizzy", "dead"]),
  entry("🤯", "exploding head", "smileys", ["mindblown", "shock"]),
  entry("🤠", "cowboy hat face", "smileys", ["cowboy"]),
  entry("🥳", "partying face", "smileys", ["party", "celebrate"]),
  entry("😎", "smiling face with sunglasses", "smileys", ["cool", "sunglasses"]),
  entry("🤓", "nerd face", "smileys", ["geek", "glasses"]),
  entry("🧐", "face with monocle", "smileys", ["inspect"]),
  entry("😕", "confused face", "smileys", ["confused"]),
  entry("😟", "worried face", "smileys", ["worry", "sad"]),
  entry("😮", "face with open mouth", "smileys", ["surprise", "wow"]),
  entry("😲", "astonished face", "smileys", ["shock", "wow"]),
  entry("😳", "flushed face", "smileys", ["embarrassed"]),
  entry("🥺", "pleading face", "smileys", ["please", "puppy"]),
  entry("😢", "crying face", "smileys", ["sad", "tear"]),
  entry("😭", "loudly crying face", "smileys", ["sad", "sob"]),
  entry("😱", "face screaming in fear", "smileys", ["scream", "fear"]),
  entry("😞", "disappointed face", "smileys", ["sad"]),
  entry("😓", "downcast face with sweat", "smileys", ["sad", "nervous"]),
  entry("😩", "weary face", "smileys", ["tired"]),
  entry("😤", "face with steam from nose", "smileys", ["triumph", "huff"]),
  entry("😡", "enraged face", "smileys", ["angry", "mad"]),
  entry("😠", "angry face", "smileys", ["mad"]),
  entry("🤬", "face with symbols on mouth", "smileys", ["swear", "angry"]),
  entry("😈", "smiling face with horns", "smileys", ["devil"]),
  entry("💀", "skull", "smileys", ["dead", "skull"]),
  entry("💩", "pile of poo", "smileys", ["poop"]),
  entry("👻", "ghost", "smileys", ["boo", "halloween"]),
  entry("👽", "alien", "smileys", ["ufo"]),
  entry("🤖", "robot", "smileys", ["bot"]),
  entry("👋", "waving hand", "people", ["wave", "hello", "hi", "bye"]),
  entry("🤚", "raised back of hand", "people", ["hand"]),
  entry("✋", "raised hand", "people", ["stop", "hand"]),
  entry("👌", "ok hand", "people", ["ok", "okay"]),
  entry("✌️", "victory hand", "people", ["peace", "yeah"]),
  entry("🤞", "crossed fingers", "people", ["luck"]),
  entry("👍", "thumbs up", "people", ["yes", "like", "ok"]),
  entry("👎", "thumbs down", "people", ["no", "dislike"]),
  entry("✊", "raised fist", "people", ["fist", "power"]),
  entry("👊", "oncoming fist", "people", ["punch", "fistbump"]),
  entry("👏", "clapping hands", "people", ["clap", "applause"]),
  entry("🙌", "raising hands", "people", ["hooray", "celebrate"]),
  entry("👐", "open hands", "people", ["hands"]),
  entry("🤝", "handshake", "people", ["deal", "agree"]),
  entry("🙏", "folded hands", "people", ["please", "thanks", "pray"]),
  entry("💪", "flexed biceps", "people", ["strong", "flex"]),
  entry("🫶", "heart hands", "people", ["love", "heart"]),
  entry("👀", "eyes", "people", ["look", "see"]),
  entry("🧠", "brain", "people", ["think", "mind"]),
  entry("🐶", "dog face", "nature", ["dog", "pet"]),
  entry("🐱", "cat face", "nature", ["cat", "pet"]),
  entry("🐭", "mouse face", "nature", ["mouse"]),
  entry("🐹", "hamster", "nature", ["pet"]),
  entry("🐰", "rabbit face", "nature", ["bunny"]),
  entry("🦊", "fox", "nature", ["fox"]),
  entry("🐻", "bear", "nature", ["bear"]),
  entry("🐼", "panda", "nature", ["panda"]),
  entry("🐨", "koala", "nature", ["koala"]),
  entry("🐯", "tiger face", "nature", ["tiger"]),
  entry("🦁", "lion", "nature", ["lion"]),
  entry("🐮", "cow face", "nature", ["cow"]),
  entry("🐷", "pig face", "nature", ["pig"]),
  entry("🐸", "frog", "nature", ["frog"]),
  entry("🐵", "monkey face", "nature", ["monkey"]),
  entry("🐔", "chicken", "nature", ["chicken"]),
  entry("🐧", "penguin", "nature", ["penguin"]),
  entry("🐦", "bird", "nature", ["bird"]),
  entry("🐤", "baby chick", "nature", ["chick", "bird"]),
  entry("🦆", "duck", "nature", ["duck"]),
  entry("🦉", "owl", "nature", ["owl"]),
  entry("🐺", "wolf", "nature", ["wolf"]),
  entry("🐗", "boar", "nature", ["boar"]),
  entry("🐴", "horse face", "nature", ["horse"]),
  entry("🦄", "unicorn", "nature", ["unicorn", "magic"]),
  entry("🐝", "honeybee", "nature", ["bee"]),
  entry("🦋", "butterfly", "nature", ["butterfly"]),
  entry("🌸", "cherry blossom", "nature", ["flower", "spring"]),
  entry("🌹", "rose", "nature", ["flower", "love"]),
  entry("🌻", "sunflower", "nature", ["flower"]),
  entry("🌼", "blossom", "nature", ["flower"]),
  entry("🌷", "tulip", "nature", ["flower"]),
  entry("🌱", "seedling", "nature", ["plant", "grow"]),
  entry("🌲", "evergreen tree", "nature", ["tree"]),
  entry("🌳", "deciduous tree", "nature", ["tree"]),
  entry("🌴", "palm tree", "nature", ["tree", "beach"]),
  entry("🌵", "cactus", "nature", ["desert"]),
  entry("🍀", "four leaf clover", "nature", ["luck", "clover"]),
  entry("🍁", "maple leaf", "nature", ["fall", "leaf"]),
  entry("🌙", "crescent moon", "nature", ["night", "moon"]),
  entry("⭐", "star", "nature", ["star"]),
  entry("🌟", "glowing star", "nature", ["star", "sparkle"]),
  entry("☀️", "sun", "nature", ["sun", "weather"]),
  entry("☁️", "cloud", "nature", ["cloud", "weather"]),
  entry("🌧️", "cloud with rain", "nature", ["rain", "weather"]),
  entry("❄️", "snowflake", "nature", ["snow", "cold"]),
  entry("⚡", "high voltage", "nature", ["zap", "lightning"]),
  entry("🔥", "fire", "nature", ["hot", "lit"]),
  entry("💧", "droplet", "nature", ["water", "drop"]),
  entry("🌈", "rainbow", "nature", ["pride", "weather"]),
  entry("🍏", "green apple", "food", ["apple", "fruit"]),
  entry("🍎", "red apple", "food", ["apple", "fruit"]),
  entry("🍐", "pear", "food", ["fruit"]),
  entry("🍊", "tangerine", "food", ["orange", "fruit"]),
  entry("🍋", "lemon", "food", ["fruit"]),
  entry("🍌", "banana", "food", ["fruit"]),
  entry("🍉", "watermelon", "food", ["fruit"]),
  entry("🍇", "grapes", "food", ["fruit"]),
  entry("🍓", "strawberry", "food", ["fruit", "berry"]),
  entry("🫐", "blueberries", "food", ["fruit", "berry"]),
  entry("🍑", "peach", "food", ["fruit"]),
  entry("🍒", "cherries", "food", ["fruit"]),
  entry("🥝", "kiwi fruit", "food", ["fruit"]),
  entry("🍅", "tomato", "food", ["veggie"]),
  entry("🥑", "avocado", "food", ["fruit"]),
  entry("🌽", "ear of corn", "food", ["veggie"]),
  entry("🌶️", "hot pepper", "food", ["spicy"]),
  entry("🥕", "carrot", "food", ["veggie"]),
  entry("🥐", "croissant", "food", ["bread", "breakfast"]),
  entry("🍞", "bread", "food", ["toast"]),
  entry("🧀", "cheese wedge", "food", ["cheese"]),
  entry("🥚", "egg", "food", ["breakfast"]),
  entry("🍳", "cooking", "food", ["egg", "breakfast"]),
  entry("🥞", "pancakes", "food", ["breakfast"]),
  entry("🥓", "bacon", "food", ["breakfast", "meat"]),
  entry("🍔", "hamburger", "food", ["burger"]),
  entry("🍟", "french fries", "food", ["fries"]),
  entry("🍕", "pizza", "food", ["slice"]),
  entry("🌭", "hot dog", "food", ["sausage"]),
  entry("🥪", "sandwich", "food", ["lunch"]),
  entry("🌮", "taco", "food", ["mexican"]),
  entry("🌯", "burrito", "food", ["mexican"]),
  entry("🥗", "green salad", "food", ["salad"]),
  entry("🍜", "steaming bowl", "food", ["ramen", "noodles"]),
  entry("🍝", "spaghetti", "food", ["pasta"]),
  entry("🍣", "sushi", "food", ["fish", "japan"]),
  entry("🍱", "bento box", "food", ["lunch"]),
  entry("🍦", "soft ice cream", "food", ["dessert", "icecream"]),
  entry("🍩", "doughnut", "food", ["dessert", "donut"]),
  entry("🍪", "cookie", "food", ["dessert"]),
  entry("🎂", "birthday cake", "food", ["cake", "party"]),
  entry("🍰", "shortcake", "food", ["cake", "dessert"]),
  entry("🍫", "chocolate bar", "food", ["dessert"]),
  entry("🍿", "popcorn", "food", ["movie"]),
  entry("☕", "hot beverage", "food", ["coffee", "tea"]),
  entry("🍵", "teacup without handle", "food", ["tea"]),
  entry("🍺", "beer mug", "food", ["drink", "alcohol"]),
  entry("🍻", "clinking beer mugs", "food", ["cheers", "drink"]),
  entry("🍷", "wine glass", "food", ["drink", "alcohol"]),
  entry("🥤", "cup with straw", "food", ["soda", "drink"]),
  entry("⚽", "soccer ball", "activity", ["football", "sport"]),
  entry("🏀", "basketball", "activity", ["sport"]),
  entry("🏈", "american football", "activity", ["sport"]),
  entry("⚾", "baseball", "activity", ["sport"]),
  entry("🎾", "tennis", "activity", ["sport"]),
  entry("🏐", "volleyball", "activity", ["sport"]),
  entry("🎱", "pool 8 ball", "activity", ["billiards"]),
  entry("🏓", "ping pong", "activity", ["table tennis"]),
  entry("🎯", "bullseye", "activity", ["target", "darts"]),
  entry("🎮", "video game", "activity", ["controller", "play"]),
  entry("🎲", "game die", "activity", ["dice", "game"]),
  entry("♟️", "chess pawn", "activity", ["chess"]),
  entry("🧩", "puzzle piece", "activity", ["puzzle"]),
  entry("🎨", "artist palette", "activity", ["art", "paint"]),
  entry("🎭", "performing arts", "activity", ["theatre", "drama"]),
  entry("🎬", "clapper board", "activity", ["movie", "film"]),
  entry("🎤", "microphone", "activity", ["sing", "karaoke"]),
  entry("🎧", "headphone", "activity", ["music"]),
  entry("🎼", "musical score", "activity", ["music"]),
  entry("🎹", "musical keyboard", "activity", ["piano", "music"]),
  entry("🥁", "drum", "activity", ["music"]),
  entry("🎸", "guitar", "activity", ["music"]),
  entry("🎺", "trumpet", "activity", ["music"]),
  entry("🎻", "violin", "activity", ["music"]),
  entry("🎉", "party popper", "activity", ["party", "celebrate", "tada"]),
  entry("🎊", "confetti ball", "activity", ["party", "celebrate"]),
  entry("🎈", "balloon", "activity", ["party"]),
  entry("🎁", "wrapped gift", "activity", ["present", "birthday"]),
  entry("🏆", "trophy", "activity", ["win", "award"]),
  entry("🥇", "1st place medal", "activity", ["gold", "win"]),
  entry("🏅", "sports medal", "activity", ["award"]),
  entry("🚗", "automobile", "travel", ["car"]),
  entry("🚕", "taxi", "travel", ["cab"]),
  entry("🚌", "bus", "travel", ["bus"]),
  entry("🏎️", "racing car", "travel", ["race"]),
  entry("🚓", "police car", "travel", ["police"]),
  entry("🚑", "ambulance", "travel", ["emergency"]),
  entry("🚒", "fire engine", "travel", ["fire"]),
  entry("🚜", "tractor", "travel", ["farm"]),
  entry("🚲", "bicycle", "travel", ["bike"]),
  entry("🛵", "motor scooter", "travel", ["scooter"]),
  entry("🏍️", "motorcycle", "travel", ["bike"]),
  entry("✈️", "airplane", "travel", ["plane", "flight"]),
  entry("🚀", "rocket", "travel", ["space", "launch"]),
  entry("🛸", "flying saucer", "travel", ["ufo"]),
  entry("🚁", "helicopter", "travel", ["chopper"]),
  entry("🚂", "locomotive", "travel", ["train"]),
  entry("🚢", "ship", "travel", ["boat"]),
  entry("⛵", "sailboat", "travel", ["boat"]),
  entry("🏠", "house", "travel", ["home"]),
  entry("🏡", "house with garden", "travel", ["home"]),
  entry("🏢", "office building", "travel", ["work"]),
  entry("🏥", "hospital", "travel", ["health"]),
  entry("🏫", "school", "travel", ["school"]),
  entry("🏰", "castle", "travel", ["castle"]),
  entry("⛪", "church", "travel", ["church"]),
  entry("🗼", "tokyo tower", "travel", ["tokyo"]),
  entry("🗽", "statue of liberty", "travel", ["new york"]),
  entry("⛺", "tent", "travel", ["camp"]),
  entry("🗺️", "world map", "travel", ["map"]),
  entry("🌍", "globe europe-africa", "travel", ["world", "earth"]),
  entry("🌎", "globe americas", "travel", ["world", "earth"]),
  entry("🌏", "globe asia-australia", "travel", ["world", "earth"]),
  entry("⌚", "watch", "objects", ["time"]),
  entry("📱", "mobile phone", "objects", ["phone"]),
  entry("💻", "laptop", "objects", ["computer"]),
  entry("⌨️", "keyboard", "objects", ["computer"]),
  entry("🖥️", "desktop computer", "objects", ["computer"]),
  entry("🖨️", "printer", "objects", ["print"]),
  entry("🖱️", "computer mouse", "objects", ["mouse"]),
  entry("💾", "floppy disk", "objects", ["save"]),
  entry("📷", "camera", "objects", ["photo"]),
  entry("📹", "video camera", "objects", ["video"]),
  entry("📺", "television", "objects", ["tv"]),
  entry("💡", "light bulb", "objects", ["idea", "light"]),
  entry("🔦", "flashlight", "objects", ["light"]),
  entry("📖", "open book", "objects", ["read", "book"]),
  entry("📚", "books", "objects", ["library"]),
  entry("✏️", "pencil", "objects", ["write"]),
  entry("✒️", "black nib", "objects", ["write", "pen"]),
  entry("🖊️", "pen", "objects", ["write"]),
  entry("📎", "paperclip", "objects", ["clip"]),
  entry("📌", "pushpin", "objects", ["pin"]),
  entry("📍", "round pushpin", "objects", ["location", "pin"]),
  entry("✂️", "scissors", "objects", ["cut"]),
  entry("🔒", "locked", "objects", ["lock", "secure"]),
  entry("🔓", "unlocked", "objects", ["unlock"]),
  entry("🔑", "key", "objects", ["password"]),
  entry("🔨", "hammer", "objects", ["tool", "fix"]),
  entry("🛠️", "hammer and wrench", "objects", ["tools"]),
  entry("⚙️", "gear", "objects", ["settings"]),
  entry("🧲", "magnet", "objects", ["attract"]),
  entry("🧪", "test tube", "objects", ["science"]),
  entry("🔭", "telescope", "objects", ["space", "look"]),
  entry("🧰", "toolbox", "objects", ["tools"]),
  entry("💎", "gem stone", "objects", ["diamond", "jewel"]),
  entry("💰", "money bag", "objects", ["money"]),
  entry("💵", "dollar banknote", "objects", ["money"]),
  entry("✉️", "envelope", "objects", ["mail", "email"]),
  entry("📦", "package", "objects", ["box", "ship"]),
  entry("📅", "calendar", "objects", ["date"]),
  entry("⏰", "alarm clock", "objects", ["time", "alarm"]),
  entry("⏳", "hourglass flowing sand", "objects", ["wait", "time"]),
  entry("❤️", "red heart", "symbols", ["heart", "love"]),
  entry("🧡", "orange heart", "symbols", ["heart", "love"]),
  entry("💛", "yellow heart", "symbols", ["heart", "love"]),
  entry("💚", "green heart", "symbols", ["heart", "love"]),
  entry("💙", "blue heart", "symbols", ["heart", "love"]),
  entry("💜", "purple heart", "symbols", ["heart", "love"]),
  entry("🖤", "black heart", "symbols", ["heart", "love"]),
  entry("🤍", "white heart", "symbols", ["heart", "love"]),
  entry("🤎", "brown heart", "symbols", ["heart", "love"]),
  entry("💔", "broken heart", "symbols", ["heart", "sad"]),
  entry("❣️", "heart exclamation", "symbols", ["heart", "love"]),
  entry("💕", "two hearts", "symbols", ["heart", "love"]),
  entry("💞", "revolving hearts", "symbols", ["heart", "love"]),
  entry("💓", "beating heart", "symbols", ["heart", "love"]),
  entry("💗", "growing heart", "symbols", ["heart", "love"]),
  entry("💖", "sparkling heart", "symbols", ["heart", "love"]),
  entry("💘", "heart with arrow", "symbols", ["heart", "love"]),
  entry("💝", "heart with ribbon", "symbols", ["heart", "love", "gift"]),
  entry("✨", "sparkles", "symbols", ["shine", "magic"]),
  entry("⚡", "high voltage", "symbols", ["zap", "energy"]),
  entry("💯", "hundred points", "symbols", ["100", "perfect"]),
  entry("✅", "check mark button", "symbols", ["done", "yes", "check"]),
  entry("✔️", "check mark", "symbols", ["done", "yes"]),
  entry("❌", "cross mark", "symbols", ["no", "x"]),
  entry("❗", "exclamation mark", "symbols", ["alert"]),
  entry("❓", "question mark", "symbols", ["question"]),
  entry("➕", "plus", "symbols", ["add"]),
  entry("➖", "minus", "symbols", ["subtract"]),
  entry("➡️", "right arrow", "symbols", ["arrow"]),
  entry("⬅️", "left arrow", "symbols", ["arrow"]),
  entry("⬆️", "up arrow", "symbols", ["arrow"]),
  entry("⬇️", "down arrow", "symbols", ["arrow"]),
  entry("♻️", "recycling symbol", "symbols", ["recycle"]),
  entry("⚠️", "warning", "symbols", ["caution"]),
  entry("🚫", "prohibited", "symbols", ["no", "stop"]),
  entry("🔞", "no one under eighteen", "symbols", ["nsfw"]),
  entry("💤", "zzz", "symbols", ["sleep"]),
  entry("🎵", "musical note", "symbols", ["music"]),
  entry("🎶", "musical notes", "symbols", ["music"]),
];

export function filterEmoji(query: string, category?: EmojiCategory) {
  const needle = query.trim().toLowerCase();
  return EMOJI_CATALOG.filter((item) => {
    if (needle) {
      const haystack = `${item.name} ${item.keywords.join(" ")}`.toLowerCase();
      return haystack.includes(needle);
    }
    return category == null || item.category === category;
  });
}

export function insertAtCursor(text: string, insert: string, start: number, end: number) {
  const lower = Math.max(0, Math.min(start, end, text.length));
  const upper = Math.max(0, Math.min(Math.max(start, end), text.length));
  return {
    text: `${text.slice(0, lower)}${insert}${text.slice(upper)}`,
    caret: lower + insert.length,
  };
}
